ExamensArbeteMVC/Models/ContactFormModel.cs
using Microsoft.Build.Framework;
using System.ComponentModel.DataAnnotations;
using RequiredAttribute = System.ComponentModel.DataAnnotations.RequiredAttribute;

namespace ExamensArbeteMVC.Models
{
    public class ContactFormModel
    {

        [Required(ErrorMessage = "Please enter your name")]
        [StringLength(25, MinimumLength = 2)]

        public string? Name { get; set; }
        [Required(ErrorMessage = "Please enter your lastName")]
        [StringLength(25, MinimumLength = 2)]

        public string? AfterName { get; set; }

        [Required]
        [StringLength(25, MinimumLength = 2)]

        public string? Adress { get; set; }

        [Required(ErrorMessage = "Please enter your email")]
        [RegularExpression("^[a-z0-9._\\.-]+@([a-z0-9-]+\\.)+[a-z]{2,3}$", ErrorMessage = "Invalid Email Address")]
        public string? Email { get; set; }

        [Required]
        [StringLength(1000, MinimumLength = 5)]
        public string? Message { get; set; }

        //public DateTime SendAt { get; set; }

        //public DateTime UtcNow { get; internal set; }
    }
}

ExamensArbeteMVC/Models/CourseModel.cs
using System.ComponentModel.DataAnnotations;

namespace ExamensArbeteMVC.Models
{
    public class CourseModel
    {
        [Key]

        public int? Id { get; set; }
        public string? Title { get; set; }
        public string? description { get; set; }
        public string? Teacher { get; set; }
        public string? price { get; set; }

        public string? startDate { get; set; }
        public string? ImagesPath { get; set; }

    
    }
    }

ExamensArbeteMVC/Models/ErrorViewModel.cs
namespace ExamensArbeteMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamensArbeteMVC/Models/LogInModel.cs
using System.ComponentModel.DataAnnotations;
namespace ExamensArbeteMVC.Models
{
    public class LogInModel
    {

        [Required(ErrorMessage = "Write youe Email, please ")]
        [RegularExpression("^[a-z0-9._\\.-]+@([a-z0-9-]+\\.)+[a-z]{2,3}$", ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }


        [Required(ErrorMessage = "Choose a password, please ")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Display(Name ="Remember me")]
        public bool RememberMe { get; set; }
    }
}

ExamensArbeteMVC/Models/SignUpModel.cs
using System.ComponentModel.DataAnnotations;

namespace ExamensArbeteMVC.Models
{
    public class SignUpModel
    {
        [Required (ErrorMessage = "Write youe Email, please ")]
        [RegularExpression("^[a-z0-9._\\.-]+@([a-z0-9-]+\\.)+[a-z]{2,3}$", ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Choose a password, please ")]
        [Compare("ConfirmPassword", ErrorMessage ="Password dosn't match")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Confirm your password, please")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        public string ConfirmPassword { get; set; }

    }
}

ExamensArbeteMVC/Controllers/AccountController.cs
using ExamensArbeteMVC.Models;
using ExamensArbeteMVC.RepositoryData;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;


namespace ExamensArbeteMVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountData _accountData;

        public readonly SignInManager<IdentityUser> SignInManager;
        public AccountController(IAccountData accountData, SignInManager<IdentityUser> signInManager)
        {
            _accountData = accountData;
            SignInManager = signInManager;
        }
        [Route("signup")]
        public IActionResult SignUp()
        {
            return View();
        }
        //public IActionResult SignUp(bool isSuccess = false)
        //{
        //    ViewBag.IsSuccess = isSuccess;
        //    return View();
        //}
        [Route("signup")]
        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpModel userModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _accountData.CreateUserAsync(userModel);
                if (result.Succeeded)
                {
                    TempData["Message"] = "Your account has been created successfully. You can log in now";
                    return RedirectToAction("LogIn", "Account");
                }
                ModelState.AddModelError("", "Invalid input");
            }
            return View(userModel);
        }

        [Route("login")]
        public IActionResult LogIn()
        {
            return View();
        }
        [Route("login")]
        [HttpPost]
        public async Task<IActionResult> LogIn(LogInModel loginModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _accountData.PasswordSignInAsync(loginModel);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", "Invalid input");
            }
            return View(loginModel);
        }

        [Route("logout")]
        public async Task<IActionResult> LogOut()
        {
            await _accountData.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

ExamensArbeteMVC/Controllers/CourseController.cs
using ExamensArbeteMVC.Models;
using ExamensArbeteMVC.RepositoryData;
using Microsoft.AspNetCore.Mvc;

namespace ExamensArbeteMVC.Controllers
{
    public class CourseController : Controller
    {


        private readonly ICourseData _courseData = null;

        public CourseController(ICourseData courseData)
        {
            _courseData = courseData;
        }

        [Route("all-courses")]
        public async Task<ViewResult> GetAllCourses()
        {
            var data = await _courseData.GetAllCourses();
            return View(data);
        }
     
        public async Task<IActionResult> GetCourseId(int id)
        {
            var course = await _courseData.GetCourse(id);

            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

      




    }
}

ExamensArbeteMVC/Controllers/FormController.cs
// I detta klass jag skapar två metoder en för Get så att användra kan se formuläret och fylla i den
// och det andra För POST för att kunna skicka förmuläret till Databasen
using ExamensArbeteMVC.Models;
using ExamensArbeteMVC.RepositoryData;
using Microsoft.AspNetCore.Mvc;

namespace ExamensArbeteMVC.Controllers
{
    public class FormController : Controller
    {
        private readonly FormData _courseData = null;
        public FormController(FormData courseData)
        {
            _courseData = courseData;
        }
        public ViewResult ContactForm(bool isSuccess = false, int courseId = 0)
        {
            ViewBag.IsSuccess = isSuccess;
            ViewBag.courseId = courseId;
            return View();
        }
        [HttpPost]
        //I use IactionResult to return any type of return method
        public async Task<IActionResult> ContactForm(ContactFormModel contactFormModel)
        {
            if (ModelState.IsValid)
            {
                //when the id is bigger than 0, then it will redirect us to the form
                int id = await _courseData.ContactForm(contactFormModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(ContactForm), new { isSuccess = true });
                }
            }
              
            return View();

        }

    }
}

ExamensArbeteMVC/Controllers/HomeController.cs
using ExamensArbeteMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;

namespace ExamensArbeteMVC.Controllers
{
    public class HomeController : Controller
    {


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AboutUs()
        {
            return View();
        }

        //public IActionResult ContactUs()
        //{
        //    return View();
        //}
    }
}

ExamensArbeteMVC/Views/Course/GetAllCourses.cshtml
@using ExamensArbeteMVC.DBcontext;
@using ExamensArbeteMVC.Models;
@using ExamensArbeteMVC.RepositoryData;


<div class="container">
    <partial name="_AllCoursesInfo" />
</div>

ExamensArbeteMVC/Views/Course/GetCourseId.cshtml
@{
    ViewData["Title"] = "GetCourseId";
}

@using ExamensArbeteMVC.DBcontext;
@using ExamensArbeteMVC.Models;
@using ExamensArbeteMVC.RepositoryData;


@model CourseModel

<div class="container">
    <partial name="_CourseInfo" />
        </div>
        <br />

ExamensArbeteMVC/Views/Form/ContactForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ContactFormModel
@*
<div class=" angled-gradient">*@
<div class="container">
    <h1>Contact Us</h1>
    <hr />
   
    <br />
    <div class="row">

        <div class="col-6">
            <h5>
                Would you like to know more about how it works with booking our courses, <br /> the costs and more about proceed? <br />
                Write to us via the form and we will contact you shortly.
            </h5>
            <br />
            <div class="card  shadow" style="padding-top: 5px">
                <div class="card-body">
                    @if (ViewBag.IsSuccess == true)
                    {
                        <div class="alert alert-success" role="alert">
                            <div class="row flex-sm-row-reverse ">

                                <button  class="btn-close" data-dismiss="alert" aria-label="Close">
                                @*<span aria-hidden="true">&times;</span>*@
                            </button>
                                <h4 class="alert-heading">Thank you!</h4>
                            </div>
                            <p>We are thrilled to hear from you. We are processing your request and will return your contact as soon as possible....</p>
                            <hr>
                            <p class="mb-0"> We are very happy to have you with us. We hope you find a useful course.</p>
                            <br>
                           
                        </div>
                    }

                    <form method="post" asp-action="ContactForm" asp-controller="Form">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name">First Name:</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>

                        <label asp-for="AfterName">Last Name:</label>
                        <input asp-for="AfterName" class="form-control" />
                        <span asp-validation-for="AfterName" class="text-danger"></span>
                        <div class="form-group">

                            <label asp-for="Adress">Adress:</label>
                            <input asp-for="Adress" class="form-control" />
                            <span asp-validation-for="Adress" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="Email">Email:</label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">

                            <label asp-for="Message">Message:</label>
                            <textarea asp-for="Message" class="form-control"> </textarea>
                            <span asp-validation-for="Message" class="text-danger"></span>
                        </div>

                        <br />
                        <br />
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary" value="Contact us">Send</button>
                        </div>


                    </form>

                </div>

            </div>

        </div>

        <div class="col-6" style="text-align:center">
            <img src="~/Images/ContactUs.jpg" class="img-fluid" width="500" height="500" />
        </div>

    </div>



</div>
@*</div>*@

ExamensArbeteMVC/Views/Home/AboutUs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div >
<img style="padding-top: 0px" class ="Backgroung-img"src = "~/Images/AboutusTeam.png"   class="img-fluid" alt="Responsive image" width="100%" />
 <div class="top-left">
        <h1 style="font-weight: bold;" >Your way to a new future</h1>
        <h5>Our programs are the first step on your path to a brighter <br /> and more successful future.</h5>
        <h5>Let us guide you on your journey to a brighter future.</h5>
        <h5>In this website we invite you to read more about our courses and <br />and find our contact information. </h5>
 <br />
 <div class="container" style="text-align: center" >
    <a  asp-controller="Form" asp-action="ContactForm" type="button"  class="btn btn-outline-primary btn-lg" value="About us">Contact us</a>
</div>
</div>
</div>

<div class=" AboutUsBK">
    <div class="row">
        <div class="col-md-4">
            <img style="padding-bottom: 0px" class="Backgroung-img" src="~/Images/Ques.png" class="img-fluid" alt="Responsive image" width="80%" />
        </div>

    <div class=" col-md-6 top-right">
            <h1 style="font-weight: bold;" >Welcome to SkillStream's curriculum.</h1>
        <br />
        <h5>
            SkillSteam is a proven path to your first software developer job.
            Many people have gotten developer jobs after completing this skills
        </h5>
        <h5>If you are new to programming, we recommend you start at the beginning and earn these certifications in order.</h5>
        <h5>To earn each certification, build its 5 required projects and get all their tests to pass.</h5>
        <h5>You can add these certifications to your résumé or LinkedIn. But more important than the certifications is the practice you get along the way.
        </h5>
        <h5>
            If you feel overwhelmed, that is normal. Programming is hard.
            Practice is the key. Practice, practice, practice.
        </h5>
        <h5>Happy coding!</h5>
    </div>
   
    </div>
</div>


  @*  <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center">
                    <h1 class=" text-black">Heading</h1>
                    <p class=" text-black" >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec quis nulla vel velit dignissim faucibus. Sed auctor, libero a sagittis imperdiet, urna mauris rutrum augue, sit amet placerat ex nibh sed tellus.</p>
                </div>
                <div class="col-md-6 d-flex align-items-center justify-content-center">
                    <img src="~/Images/aboutus1.jpg" alt="image" width="300"  >
                </div>
            </div>
        </div>
    </div>*@

@*    <div class="container ">
        <div class="row options">

            <div class="">
                <div class="wrap">
                    <img class="blockico rounded-circle shadow" src="~/Images/aboutus1.jpg" width="200" height="200">
                    <br />
                <div class="aboutText container">
                        <h5><span style="font-size: 28px; font-family:'Times New Roman'">''</span> When you look up from your small group and everyone is doing what they are supposed too! so happy to be a member of this organization<span style="font-size: 28px; font-family:'Times New Roman'">''</span></h5>
                <h5>-Anna Kane</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <br />

    <div class="container ">
        <div class="row options">

            <div class="">
                <div class="wrap">
                    <img class="blockico rounded-circle shadow" src="~/Images/aboutUs2.jpg" width="200" height="200">
                    <br />
                    <div class="aboutText container">
                        <h5> " When you look up from your small group and everyone is doing what they are supposed too! so happy to be a member of this organization"</h5>
                        <h5>-Anna Kane</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
*@

ExamensArbeteMVC/Views/Home/ContactUs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ContactFormModel


<div class="container">
    <h1>Contact us:</h1>
    <h6>Would you like to know more about how it works with booking our courses, the costs and more about proceed? <br />
Write to us via the form and we will contact you shortly.</h6>
<div class="card  shadow">
     <div class="card-body">

<form method="post">
   
    <label asp-for="Name">Your Name:</label>
    <input asp-for="Name" class="form-control" />

     <label asp-for="AfterName">AfterName:</label>
    <input asp-for="AfterName" class="form-control" />

     <label asp-for="Adress">Adress:</label>
    <input asp-for="Adress" class="form-control" />

     <label asp-for="Email">Email:</label>
    <input asp-for="Email" class="form-control"/>

     <label asp-for="Message">Message:</label>
    <textarea asp-for="Message" class="form-control"> </textarea>
     <br />
  <button type="submit" class="btn btn-primary" value="Contact us">Submit</button>
     
</form>

</div>

</div>

</div>

ExamensArbeteMVC/Views/Shared/AllCoursesInfo.cshtml
@*@using Microsoft.AspNetCore.Identity
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData ["Title"] - ExamensArbeteMVC</title>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/ExamensArbeteMVC.styles.css" asp-append-version="true" />

@inject SignInManager<IdentityUser> _signinManager
@model CourseModel


@{
    var user = _signinManager.IsSignedIn(User);
}
@if (user)
{

    <li class="nav-item  text-white">

        Hello @((User.Identity?.Name))

    </li>



    <h4>All IT & Software courses:</h4>
    <br />

    <div class="row ">
        @foreach (var course in Model)
        {
            <div class=" col-md-3 ">
                <div class="card mb-4 shadow">

                    <img class="card-img-top" src="@course.ImagesPath " asp-for="Images">

                    <div class="card-body">
                        <h5 class="card-title">@course.Title</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Teacher: @course.Teacher</li>
                        <li class="list-group-item">Price: <span style="color:red" class="original-price">@Model.price</span> <span style="color:red" class="discounted-price">Discounte 20%</span> </li>

                        <li class="list-group-item">Start date: @course.startDate</li>
                    </ul>
                    <div class="card-body">
                       <a href="@Url.Action("GetCourseId", "Course", new { id = course.Id })" class="card-link">Courses details</a>
                       
                    </div>

                </div>

            </div>
        }
    </div>
                     
              

}
else

{
    
    <h4>All IT & Software courses:</h4>
    <br />

    <div class="row ">
        @foreach (var course in Model)
        {
            <div class=" col-md-3 ">
                <div class="card mb-4 shadow">

                    <img class="card-img-top" src="@course.ImagesPath " asp-for="Images">

                    <div class="card-body">
                        <h5 class="card-title">@course.Title</h5>
                     
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Teacher: @course.Teacher</li>
                        <li class="list-group-item">Price: @course.price</li>
                        <li class="list-group-item">Start date: @course.startDate</li>
                    </ul>
                    <div class="card-body">
                       <a href="@Url.Action("GetCourseId", "Course", new { id = course.Id })" class="card-link">Courses details</a>
                       
                    </div>

                </div>

            </div>
        }
    </div>


}

*@

ExamensArbeteMVC/Views/Shared/_AllCoursesInfo.cshtml
@using Microsoft.AspNetCore.Identity
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData ["Title"] - ExamensArbeteMVC</title>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link rel="stylesheet" href="~/ExamensArbeteMVC.styles.css" asp-append-version="true" />

@inject SignInManager<IdentityUser> _signinManager



@{
    var user = _signinManager.IsSignedIn(User);
}
@if (user)
{

    <li class="nav-item  text-white">

        Hello @((User.Identity?.Name))

    </li>


     <div class="container">
        <h1 style="color:red">As a member you get 20% DISCOUNT</h1>
    <h4>All IT & Software courses:</h4>

    <br />

    <div class="row ">
        @foreach (var course in Model)
        {
            <div class=" col-md-3 ">
                <div class="card mb-4 shadow">

                    <img class="card-img-top" src="@course.ImagesPath " asp-for="Images">

                    <div class="card-body">
                            <h5 class="card-title">@course.Title</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                            <li class="list-group-item">Teacher: @course.Teacher</li>
                            <li class="list-group-item">Price: <span style="color:red" class="original-price">@course.price</span> <span style="color:red" class="discounted-price">Discounte 20%</span> </li>

                            <li class="list-group-item">Start date: @course.startDate</li>
                    </ul>
                    <div class="card-body">
                       <a href="@Url.Action("GetCourseId", "Course", new { id = course.Id })" class="card-link">Courses details</a>
                       
                    </div>

                </div>

            </div>
       }
    </div>
                     
      </div>         

}
else

{
    
    <h4>All IT & Software courses:</h4>
    <br />

    <div class="row ">
        @foreach (var course in Model)
        {
            <div class=" col-md-3 ">
                <div class="card mb-4 shadow">

                    <img class="card-img-top" src="@course.ImagesPath " asp-for="Images">

                    <div class="card-body">
                        <h5 class="card-title">@course.Title</h5>
                     
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Teacher: @course.Teacher</li>
                        <li class="list-group-item">Price: @course.price</li>
                        <li class="list-group-item">Start date: @course.startDate</li>
                    </ul>
                    <div class="card-body">
                       <a href="@Url.Action("GetCourseId", "Course", new { id = course.Id })" class="card-link">Courses details</a>
                       
                    </div>

                </div>

            </div>
        }
    </div>


}

ExamensArbeteMVC/Views/Shared/_Layout.cshtml
<div class="wrapper">
    
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamensArbeteMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExamensArbeteMVC.styles.css" asp-append-version="true" />
</head>

    <header>
         
        <nav  class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3" >
            @*<div class="container-fluid">*@
            @*   <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication</a>*@
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <a class="navbar-brand text-white logoText" href="/">
                    @*   I use asp-append-version to bring the image from server and not from memory cash*@
                    <img class="logo" src="~/Images/SkillStream.png" width="120" />
                   
                </a>
                
                <div class="collapse navbar-collapse  m-2 flex-sm-row-reverse  ">
                    <ul class="navbar-nav " >
                        <partial name="_LoginInfo" />

                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Course" asp-action="GetAllCourses">Courses</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="AboutUs">About us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Form" asp-action="ContactForm">Contact us</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
          
    </header>
    
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
   
  

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        @await RenderSectionAsync("Scripts", required: false)


    <footer class="sticky-footer">
       
        <div id="footer"  >
             <div class ="row">
            <div class = "col-md-4 " >
                <div class="del">
                <h4 style="color:white">Contact us</h4>
                <ul class ="list-unstyled">
                    <li style="color:white">Email: hedragourieh@hotmail.com</li>
                    <li style="color:white">Mobile: 0729388315</li>
                   <li style="color:white">Orieneringsstigen, 29A</li>
                        <li style="color:white">15159 Södertälje</li>
                </ul>
                </div>
            </div>
             <div class = "col-md-4 " >
                 <div class="del">
                     <br />
                    
                        <h6 style ="color:white">Copyright &copy; HED HUB @DateTime.Now.Year </h6>
                        <ul class ="list-unstyled">
                        
                          </ul>
                          </div>
               </div>
                <div class = "col-md-4 " >
                     <div class="del">
                <h4 style="color:white">Menu</h4>
                <ul class ="list-unstyled">
                    <li> <a asp-area="" asp-controller="Home" asp-action="Index" style="color:white">Home</a></li>
                    <li><a style="color:white" asp-area="" asp-controller="Home" asp-action="AboutUs">About us</a></li>
                    <li><a style="color:white" asp-controller="Form" asp-action="ContactForm">Contact us</a></li>
                    <li><a style="color:white" asp-controller="Course" asp-action="GetAllCourses">Courses</a></li>
                   
                </ul>
                 </div>
            </div>
        </div>

 </div>
    </footer>
    <br />
   
</html>
</div>

ExamensArbeteMVC/Views/Shared/_LoginInfo.cshtml
@using Microsoft.AspNetCore.Identity
  <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData ["Title"] - ExamensArbeteMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExamensArbeteMVC.styles.css" asp-append-version="true" />

@inject SignInManager<IdentityUser> _signinManager

@{
    var user = _signinManager.IsSignedIn(User);
}
@if (user)
{

    <li class="nav-item  text-white">
        
             Hello @((User.Identity?.Name))


        <a class="btn btn btn-danger" asp-action="LogOut" asp-controller="Account">Log out</a>
        
    </li> 
   
}
else

{

    <li class="nav-item logoText2" >
        <a class="btn btn-primary" asp-controller="Account" asp-action="login">Login</a>
        <a class="btn btn-primary" asp-controller="Account" asp-action="SignUp">Register</a>
    </li>

    }





  @*  @if (!_signinManager.IsSignedIn(User))*@